export const columns: any[] = [{
    title: '序号',
    render: ({ rowIndex }: any) => `${rowIndex + 1}`,
    align: 'center',
    width: 60,
}, {
    title: '租户名称',
    dataIndex: 'tenantName',
    ellipsis: true,
    tooltip: true,
}, {
    title: '租户账号',
    dataIndex: 'tenantAccount',
    ellipsis: true,
    tooltip: true,
}, {
    title: '开通应用数',
    dataIndex: 'appNum',
    align: 'center',
    width: 110,
}, {
    title: '开通项目数',
    dataIndex: 'projectNum',
    align: 'center',
    width: 110,
}, {
    title: '租户状态',
    dataIndex: 'tenantStatus',
    align: 'center',
    slotName: 'status',
    width: 90,
}, {
    title: '创建时间',
    dataIndex: 'createTime',
    align: 'center',
    width: 180,
}, {
    title: '操作',
    slotName: 'optional',
    align: 'center',
    width: 90,
}];
